config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [ :new, :create, :destroy]

  resources :conditions, only: [ :new, :create, :edit, :update, :destroy ]
  resources :students, only: [ :index, :show, :new, :create ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/condition.rb
class Condition < ApplicationRecord

  # validates :date, :comment, presence: true
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: true, length:{ maximum: 50, uniqueness: true,
                    too_long: "は最大%{count}文字まで使用できます"}

  has_many :conditions
end

app/models/user.rb
class User < ApplicationRecord

  validates :username, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }

  validate :add_errors
  def add_errors
    if User.find_by(email: email) == nil
      errors[:base] << "ログインできません"
    end
  end

  has_secure_password
  validates :password, presence: true, length: { minimum:6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ConditionsHelper, SessionsHelper
end

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController
  before_action :set_condition, only: [:edit, :update, :destroy]
  before_action :check_logging_in, only: [ :index, :show, :edit, :destroy ]

  # GET /conditions
  # GET /conditions.json
  def index
    @conditions = Condition.all
  end

  # GET /conditions/1
  # GET /conditions/1.json
  def show
    @student = Student.find(params[:id])
    @conditions = @student.conditions.order(created_at: :desc)
    @past_table = "Past Record"
    @new_table = "New Record"
  end

  # GET /conditions/new
  def new
    @condition = Condition.new
  end

  # POST /conditions
  # POST /conditions.json
  def create
    @condition = Condition.new(condition_params)
      if @condition.save
        redirect_to student_path(params[:condition][:student_id]), notice: 'new Condition was successfully created.'
      else
        @student = Student.find(params[:condition][:student_id])
        @conditions = @student.conditions.order(date: :desc)
        progress = (@student.conditions).maximum(:progress)
        @achievement = (progress * 100 / number_of_pages).round
        @past_table = "Past Record"
        @new_table = "New Record"
        render 'students/show'
      end
  end

  # GET /conditions/1/edit
  def edit
    @name = (Student.find(@condition.student_id)).name
  end

  # PATCH/PUT /conditions/1
  # PATCH/PUT /conditions/1.json
  def update
      if @condition.update(condition_params)
        redirect_to student_path(params[:condition][:student_id]), notice: 'Condition was successfully updated.'
      else
        render 'edit'
      end
  end


  # DELETE /conditions/1
  # DELETE /conditions/1.json
  def destroy
    student_id = @condition.student_id
    @condition.destroy
      redirect_to student_path(student_id), notice: 'Condition was successfully destroyed.'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_condition
      @condition = Condition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def condition_params
      params.require(:condition).permit(:progress, :date, :comment, :username, :student_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to students_path
    else
      flash[:danger] = 'You have failed logging in.'
      redirect_to new_session_path
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'You just have logged out.'
    redirect_to new_session_path
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :check_logging_in, only: [ :index, :show, :edit, :destroy ]

  # GET /students
  # GET /students.json
  def index
    #progressが大きい順に全てのconditionsを取得
    all_conditions = Condition.where.not(progress: nil).order(progress: :desc)
    #ビューでstudent_idを元にそのstudentのprogressが一番高いレコードを取ってくるために、まずはコントローラーから全てのstudent_idを取ってきて、配列に入れていく。progressが一番高いレコードから入れていくので、必然的にprogressが高い順にstudent_idが入るはずである。
    @student_ids_ordered_by_progress = Array.new
    all_conditions.each do |condition|
      if @student_ids_ordered_by_progress.index(condition.student_id) == nil
      @student_ids_ordered_by_progress << condition.student_id
      end
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @condition = Condition.new
    @conditions = @student.conditions.order(date: :desc)
    progress = (@student.conditions).maximum(:progress)
    @achievement = (progress * 100 / number_of_pages).round
    @past_table = "Past Record"
    @new_table = "New Record"
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  def create
    @student = Student.new(student_params)
    if @student.save
      #アソシエーションを使って"new"にするとそれに紐づいたnewインスタンスも作れる
      condition = @student.conditions.new
      #下記と同義
      # condition = Condition.new
      # condition.student_id = @student.id
      condition.save
      redirect_to student_path(@student.id), notice: 'Student was successfully created'
    else
      render 'new'
    end
  end


  # PATCH/PUT /students/1
  def update
      if @student.update(student_params)
        redirect_to @student, notice: 'Student was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /students/1
  def destroy
    @student.destroy
      redirect_to students_url, notice: 'Student was successfully destroyed.'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
  #diverの質問投稿のソースコードから必要なものをdocフォルダの中のそれぞれのファイルにコピペする
  #それの読み取り
  def read_original_lists(original)
    file = File.open("#{original}")
    text = file.read
    file.close
    return text
  end

  #タイトルの抜き出し
  def get_title(original_lists)
    #value=のあとの">"から探せばいいから、それのインデックスを求めて、なければnilを入れループを終了
    close_number = original_lists.index("value=")
    if close_number == nil
      return nil,0
    end
    #タイトルの抜き出し
    start_number = original_lists.index(">", close_number)
    end_number = original_lists.index("<", start_number + 1)
    title = original_lists.slice(start_number+1..end_number-1)
    return title, end_number
  end

  def make_lists(original)
    material_lists = Hash.new
    each_number = 1
    original_lists = read_original_lists(original)

    while true
      title, end_position = get_title(original_lists)
      #value=以下の">"がない、すなわちタイトルが抜き出し終わったらbreak
      break if title == nil
      material_lists["#{title}"] = each_number
      each_number += 1
      #最初にファイルから抜き取ったテキストから取得したタイトル部分を抜き取っていき、どんどん少なくしていく。
      original_lists = original_lists.slice(end_position..-1)
    end

    return material_lists
  end

  # 新しくconditionレコードを作成するときの選択肢。どこまで終わったかを選択
  def choose
    original = "doc/english_original_lists.txt"
    return make_lists(original)
  end


  #全体の進捗を計算するために全体のページ数を計算
  def number_of_pages
    original = "doc/japanese_original_lists_by_phase3.txt"
    return ((make_lists(original)).keys.length)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def check_logging_in
    unless logged_in?
      redirect_to new_session_path
    end
  end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/conditions/edit.html.erb
<h4>Editing Condition</h4>
<h4>Name:&nbsp;&nbsp;<strong><%= @name %></strong></h4>

<%= form_with(model: @condition, local: true, url: condition_path) do |form| %>
  <% if @condition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@condition.errors.count, "error") %> prohibited this condition from being saved:</h2>

      <ul>
      <% @condition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>

  <div class="field">
    <%= form.label :progress %>
    <%= form.select :progress, choose,
    { include_blank: '選択してください' }  %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <%= form.hidden_field :username, :value => "#{current_user.username}" %>
  <%= form.hidden_field :student_id, :value => "#{@condition.student_id}" %>



  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

<%= link_to 'Back', student_path(@condition.student_id) %>

app/views/conditions/new.html.erb
<h1>New Condition</h1>

<%= render 'form', condition: @condition %>

<%= link_to 'Back', conditions_path %>

app/views/conditions/show.html.erb
<p id="notice"><%= notice %></p>

<h4>Name:&nbsp;&nbsp;<strong><%= @student.name %></strong></h4>
<div class="row">
  <div class="col-xs-offset-10 co-xs-2">
    <%= link_to '一覧へ戻る', students_path, class: 'btn btn-default' %>
  </div>
</div>

<p>
  <strong>Progress:</strong>
  <div class="progress">
    <div class="progress-bar" role="progressbar" aria-valuenow="<%= current_progress %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= current_progress %>%;">
      <%= current_progress %>%
    </div>
  </div>
</p>
<p>&nbsp;</p>

<div class="panel panel-default">
  <div class="panel-heading"><%= @past_table %></div>
  <table class="table">
    <tr>
      <th>Date</th>
      <th>User</th>
      <th>comment</th>
    </tr>
    <% @conditions.each do |condition| %>
      <tr>
        <td><%= condition.date %></td>
        <td><%= condition.username %></td>
        <td><%= condition.comment %></td>
      </tr>
    <% end %>
  </table>
</div>


<%= form_with(model: Condition.new, local: true) do |form| %>

  <div class="panel panel-danger">
    <div class="panel-heading"><%= @new_table %></div>
    <table class="table">
      <tr>
        <%= form.label :progress %>
        <%= form.select :progress, choose,
        { include_blank: '選択してください' }  %>
      </tr>

      <tr>
        <th>Date</th>
        <th>User</th>
        <th>comment</th>
      </tr>

      <tr>
        <td><%= form.date_field :date %></td>
        <td>
          <%= form.select :username, ['Kawasaki', 'Yamamoto'],
                        { include_blank: '選択してください' }  %>
        </td>
        <td><%= form.text_area :comment %></td>
      </tr>
    </table>
  </div>

  <%= form.hidden_field :student_id, :value => "#{@student.id}" %>

  <%= form.submit 'Add' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Progress</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">Progress</a>
            <ul class="nav navbar-nav">
              <% if logged_in? %>
                <li><%= link_to "All", students_path %></li>
                <li><%= link_to "Log out", session_path(current_user.id), method: :delete %></li>
                <li><%= link_to "#{@current_user.username}"  %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>



    <%= yield %>

    </div>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :student_name %>
  </div>

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h1>All Students</h1></div>
  <table class="table">
    <tr>
      <th class="col-xs-3">Name</th>
      <th class="col-xs-5">Progress</th>
      <th  class="col-xs-4">Comment</th>
    </tr>
    <% @student_ids_ordered_by_progress.each do |student_id| %>
      <% student_conditions = Student.find(student_id).conditions.order(date: :desc) %>
      <% progress = student_conditions.maximum(:progress) %>
      <% achievement = (progress * 100 / number_of_pages).round %>
      <tr>
        <td><%= link_to "#{Student.find(student_id).name}", student_path(student_id) %></td>
        <td>
          <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="<%= achievement %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= achievement %>%;">
              <%= achievement %>%
            </div>
          </div>
          <!-- progressバーで表示されているページのタイトル -->
          <p class="title_of_progress"><%= choose.key(progress) %></p>
        </td>
        <td>
          <p class="comment"><%= student_conditions.first.comment %></p>
          <p class="date"><%= student_conditions.first.date %>&nbsp;&nbsp;<%= student_conditions.first.username %></p>
      </tr>
    <% end %>
  </table>
</div>

<br>

<%= link_to 'New Student', new_student_path, class: 'btn btn-default' %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<h4>Name:&nbsp;&nbsp;<strong><%= @student.name %></strong></h4>
<div class="row">
  <div class="col-xs-offset-10 co-xs-2">
    <%= link_to 'back to All', students_path, class: 'btn btn-default' %>
  </div>
</div>

<p>
  <strong>Progress:</strong>
  <div class="progress">
    <div class="progress-bar" role="progressbar" aria-valuenow="<%= @achievement %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @achievement %>%;">
      <%= @achievement %>%
    </div>
  </div>
</p>
<p>&nbsp;</p>

<div class="panel panel-default row">
  <div class="panel-heading"><%= @past_table %></div>
  <table class="table">
    <tr>
      <th class="col-xs-1">Date</th>
      <th class="col-xs-2">User</th>
      <th class="col-xs-3">Progress</th>
      <th class="col-xs-4">comment</th>
      <th class="col-xs-1">&nbsp;</th>
      <th class="col-xs-1">&nbsp;</th>
    </tr>
    <% @conditions.each do |condition| %>
      <!-- 取り出されたレコードのprogressの数字からタイトルを検索 -->
      <% progress_at_that_time = choose.key(condition.progress) %>
      <tr>
        <td><%= condition.date %></td>
        <td><%= condition.username %></td>
        <td><p class="progress_at_that_time"><%= progress_at_that_time %></p></td>
        <td><p class="comment"><%= condition.comment %></p></td>
        <td>
          <%= link_to 'Edit',
                edit_condition_path(condition.id),
                class: 'btn btn-success' %>
        </td>
        <td>
          <%= link_to 'Delete',
                condition_path(condition.id),
                data: { confirm: "Are you sure?"},
                method: :delete, class: 'btn btn-warning' %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<% if @condition.errors.any? %>
  <div id="error_explanation">
    <h2>There are <%= @condition.errors.count %>errors.</h2>
    <ul>
      <% @condition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @condition, local: true) do |form| %>

  <div class="panel panel-danger row">
    <div class="panel-heading"><%= @new_table %></div>
    <table class="table">
      <tr>
        <th class="col-md-3">Date</th>
        <th class="col-md-5">Progress</th>
        <th class="col-md-4">comment</th>
      </tr>

      <tr>
        <td><%= form.date_field :date %></td>
        <td>
          <div class="row">
            <%= form.select :progress, choose,
            { include_blank: 'Please choose' }, class: 'col-xs-11'  %>
          </div>
        </td>
        <td>
          <div class="row">
            <%= form.text_area :comment, class: "comment col-xs-11" %>
          </div>
        </td>
      </tr>
    </table>
  </div>

  <%= form.hidden_field :username, :value => "#{current_user.username}" %>
  <%= form.hidden_field :student_id, :value => "#{@student.id}" %>

  <%= form.submit 'Add' %>

<% end %>